name: Build-Test-GNU-Linux
 
on:  
  push:
    branches: [ master ] 
jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: dependecies
        run: sudo apt install python3 python3-pip python3-dev && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable

      - name: pip
        run: pip3 install setuptools==46.1 wheel setuptools-rust requests
      
      - name: compile
        run: python3 setup.py install --user
    
      - name: test
        run: python3 AnilistPython/AnilistPython/testCase.py
